### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by ianaya89**
Adding tribune dependency
Fixing ES6 syntax on bin
Adding entries to gitignore
Adding tribune deregister
Upgrading node version
Updating package.json

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Ah, very cool. Nice job @ianaya89. I'll review shortly.

**Comment by recurrence** [comment]
Sweet thanks, right when I needed it :)

**Comment by RobertWHurst** [comment]
Looks good 👍

**Comment by RobertWHurst** [comment]
Pushed to NPM. Feel free to update.

**Pull request merged**
